/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supplychainmanagementapp;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author bhaskar patidar
 */
public final class SupplierDash extends javax.swing.JFrame  {

    /**
     * Creates new form SupplierDash
     */
    Connection con=null;
    PreparedStatement pst=null,pst1=null,pst2=null;
    ResultSet rs=null,rs1 =null;

    
    public SupplierDash() {
        initComponents();
        setTitle("Supplier Dashboard");
        setSize(1000,500);
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
        dash();
        dash1();
    }
    public void dash()
    {
        UserLogin ul=new UserLogin();
        this.jLabel2.setText(UserLogin.uname);
    }
     public void dash1()
    {
        UserLogin ul=new UserLogin();
        this.jTextField1.setText(ul.uname);
    }
     public void loadDataCustomerName()
     {
         try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supply_chain_management","root","");
             if(con!=null)
             {
                 String query="select * from user_details where department='Manufacturer'";
                 pst=con.prepareStatement(query);
                 rs=pst.executeQuery();
                 while(rs.next())
                 {
                     jComboBox1.addItem(rs.getString("user_name"));
                 }
                 
             }
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
         
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addLot = new javax.swing.JButton();
        placeOrder = new javax.swing.JButton();
        orderDetails = new javax.swing.JButton();
        change_pass = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        recivedOrders = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        exp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mrp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        destination = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        company_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        destiny = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        partner = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_mode = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        place = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        prod_category = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        validate = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addLot.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        addLot.setText("Add Lot");
        addLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLotActionPerformed(evt);
            }
        });

        placeOrder.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        placeOrder.setText("Place Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });

        orderDetails.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        orderDetails.setText("Order Details");
        orderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDetailsActionPerformed(evt);
            }
        });

        change_pass.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        change_pass.setText("Change Password");
        change_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_passActionPerformed(evt);
            }
        });

        inventory.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        inventory.setText("Inventory");
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\sign out.png")); // NOI18N
        jButton6.setText("Log Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        recivedOrders.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        recivedOrders.setText("Recived Orders");
        recivedOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recivedOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recivedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(change_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(placeOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addComponent(inventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(recivedOrders)
                .addGap(35, 35, 35)
                .addComponent(addLot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(change_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 460));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\rack2.jpg")); // NOI18N
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        jTabbedPane1.addTab("front", jPanel9);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_Id", "Supplier", "Cust_Name", "Cust_Category", "Prod_Name", "Prod_Company", "Prod_Category", "Delivery_Destination", "Delivery_Partner", "Trans_Mode", "Quantity", "Shipping Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 113, 776, 291));

        jLabel20.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("Order Details");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\rack2.jpg")); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        jTabbedPane1.addTab("order details", jPanel5);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel12.setText("Product Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 68, -1, 14));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 200, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("Product Company");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 122, -1, -1));
        jPanel3.add(comName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 144, 200, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("Product Category");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 181, -1, -1));
        jPanel3.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 203, 200, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setText("Expiry Time");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        jPanel3.add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 200, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });
        jPanel3.add(quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 200, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setText("Marked Price");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));
        jPanel3.add(mrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setText("Rate");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        jPanel3.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 200, -1));

        add.setBackground(new java.awt.Color(0, 153, 255));
        add.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 392, -1, -1));

        jLabel22.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setText("Add Lot");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jTabbedPane1.addTab("Add Lot", jPanel3);

        destination.setBackground(new java.awt.Color(153, 153, 153));
        destination.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setText("Customer Name");
        destination.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 101, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel11.setText("Customer Category");
        destination.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 144, 130, 23));

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel13.setText("Product Name");
        destination.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 95, -1));

        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });
        destination.add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, -1));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel14.setText("Product Category");
        destination.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 130, -1));
        destination.add(company_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, 20));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel15.setText("Delivery Destination");
        destination.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        destination.add(destiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, -1));

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel16.setText("Delivery Partner");
        destination.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, -1));
        destination.add(partner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 200, -1));

        jLabel17.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel17.setText("Transport Mode");
        destination.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 252, 102, -1));
        destination.add(t_mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 272, 200, -1));

        jLabel18.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel18.setText("Quantity");
        destination.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 202, 55, -1));
        destination.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 222, 200, -1));

        place.setBackground(new java.awt.Color(0, 153, 255));
        place.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        place.setForeground(new java.awt.Color(255, 255, 255));
        place.setText("Place Order");
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        destination.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 402, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 153, 153));
        jLabel19.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("Place Order");
        destination.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 240, -1));

        jLabel23.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel23.setText("Product Company");
        destination.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 123, 113, -1));
        destination.add(prod_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 200, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jTextField3.setText("Manufracturer");
        destination.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 173, 200, 20));

        jComboBox1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        destination.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 200, -1));
        destination.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 200, -1));

        jLabel34.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel34.setText("Shipping Date");
        destination.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jTabbedPane1.addTab("place Order", destination);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setBackground(new java.awt.Color(204, 204, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order_Id", "Customer Name", "Product Name", "Product Category", "Quantity", "Delivery Address", "Expected Delivery Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 760, 300));

        jLabel28.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("Recived Orders");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\rack2.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 460));

        jTabbedPane1.addTab("Recived Orders", jPanel2);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel26.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel26.setText("User Name");

        jLabel27.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel27.setText("New Password");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\username.png")); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\lock.png")); // NOI18N

        validate.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        validate.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addGap(71, 71, 71)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validate)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(jTextField2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel26))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        jLabel31.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jLabel31.setText("Change Password");

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\password-reset-95.png")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(50, 50, 50))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("changePass", jPanel4);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_Id", "Product_Name", "Company", "Category", "Exp_Date", "Quantity", "MRP", "Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 97, 766, 301));

        jLabel21.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("Inventory");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhaskar patidar\\OneDrive\\Documents\\NetBeansProjects\\SupplyChainManagementApp\\src\\main\\java\\com\\mycompany\\supplychainmanagementapp\\images\\rack2.jpg")); // NOI18N
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        jTabbedPane1.addTab("inventory", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, -32, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void change_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_passActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_change_passActionPerformed

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(3);
                loadDataCustomerName();

//        jPanel3.setEnabled(true);
    }//GEN-LAST:event_placeOrderActionPerformed

    private void addLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLotActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
       
        
        
        
    }//GEN-LAST:event_addLotActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_nameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        UserLogin login=new UserLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void orderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDetailsActionPerformed
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(1);
                
                 try{
            
                        con =DriverManager.getConnection("jdbc:mysql://localhost:3306/supply_chain_management","root","");
                        if(con!=null)
                          {
                              String query="select * from orders";
                                 pst=con.prepareStatement(query);
                                 rs=pst.executeQuery();
               
                                  DefaultTableModel tb1 =(DefaultTableModel)jTable2.getModel();
                                       tb1.setRowCount(0);               
                                  while(rs.next())
                                {
                                tb1.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
                                }


                
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_orderDetailsActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
                jTabbedPane1.setSelectedIndex(6);
                try{
            
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/supply_chain_management","root","");
            
            if(con!=null)
            {
                String query="select * from product_details";
                pst1=con.prepareStatement(query);
                rs1=pst1.executeQuery();
                DefaultTableModel tb2 =(DefaultTableModel)jTable1.getModel();
                tb2.setRowCount(0);
                while(rs1.next())
                {
                    tb2.addRow(new String[]{ rs1.getString(1),rs1.getString(3),rs1.getString(4),rs1.getString(5),rs1.getString(6),rs1.getString(7),rs1.getString(8),rs1.getString(9)});
                }
                
                
                
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
                

    }//GEN-LAST:event_inventoryActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
        String url="jdbc:mysql://localhost:3306/supply_chain_management";
            String user= "root";
            String pass="";
            
            con=DriverManager.getConnection(url,user,pass);
            if(con!=null)
            {
                String supplier=jLabel2.getText();
                String P_name=name.getText();
                String P_comp=comName.getText();
                String P_cat=category.getText();
                String exp_date=exp.getText();
                int quan= Integer.parseInt(quant.getText());
                double MRP= Double.parseDouble(mrp.getText());
                double RATE = Double.parseDouble(rate.getText());
                
                String query="insert into product_details(supplier,product_name,prod_company,prod_category,exp_date,quantity,prod_mrp,prod_rate) values (?,?,?,?,?,?,?,?)";
                pst=con.prepareStatement(query);
                pst.setString(1, supplier);
                pst.setString(2, P_name);
                pst.setString(3, P_comp);
                pst.setString(4, P_cat);
                pst.setString(5, exp_date);
                pst.setInt(6, quan);
                pst.setDouble(7, MRP);
                pst.setDouble(8, RATE);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Lot Added Successfully");
                
                name.setText("");
                comName.setText("");
                category.setText("");
                exp.setText("");
                quant.setText("");
                mrp.setText("");
                rate.setText("");
            
            }
         }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        // TODO add your handling code here:
                try{
        String url="jdbc:mysql://localhost:3306/supply_chain_management";
            String user= "root";
            String pass="";
            
            con=DriverManager.getConnection(url,user,pass);
            if(con!=null)
            {
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                String date =sdf.format(jDateChooser1.getDate());
                String supplier=jLabel2.getText();
                String Product=product_name.getText();
                String custom=jComboBox1.getSelectedItem().toString();
                String custom_cat=jTextField3.getText(); 
            
                String comp=company_name.getText();
                String cat=prod_category.getText();
                String dest=destiny.getText();
                String partn=partner.getText();
                int quanti= Integer.parseInt(quantity.getText());
                String transport=t_mode.getText();
                
                String query="insert into orders(supplier_name,customer_name,customer_category,product_name,product_company,product_category,delivery_dest,delivery_partner,trans_mode,order_quantity,ship_date) values (?,?,?,?,?,?,?,?,?,?,?)";
                pst=con.prepareStatement(query);
                pst.setString(1, supplier);
                pst.setString(2, custom);
                pst.setString(3, custom_cat);
                pst.setString(4, Product);
                pst.setString(5, comp);
                pst.setString(6,cat);
                pst.setString(7, dest);
                pst.setString(8, partn);
                pst.setString(9, transport);
                pst.setInt(10, quanti);
                pst.setString(11, date);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Order Placed");
                int newQuan = 0;
                String retriveQuant="select quantity from product_details where product_name=?";
                pst2=con.prepareStatement(retriveQuant);
                pst2.setString(1, Product);
                rs1=pst2.executeQuery();
                
                if(rs1.next())
                {
                    newQuan=rs1.getInt("quantity");
                }
              
                int quantii=newQuan-quanti;
                String upQuan="update product_details set quantity=? where product_name=?";
                pst1=con.prepareStatement(upQuan);
                pst1.setInt(1, quantii);
                pst1.setString(2, Product);
                pst1.executeUpdate();
                  
                product_name.setText("");
                jComboBox1.setSelectedIndex(0);
                company_name.setText("");
                prod_category.setText("");
                quantity.setText("");
                t_mode.setText("");
                destiny.setText("");
                partner.setText("");
                
            }
                }
            catch(Exception e)
                    {
                        e.printStackTrace();
                    }
    }//GEN-LAST:event_placeActionPerformed

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String password=jTextField2.getText();
        boolean valid =true;
        if(password.length()>=8 && password.length()<=12)
        {
            valid = true;

            try
            {
                Connection con =null;
                PreparedStatement pst=null;
                String url="jdbc:mysql://localhost:3306/supply_chain_management";
                String user= "root";
                String pass="";
                con=DriverManager.getConnection(url,user,pass);
                if(con!=null)
                {
                    String username=jTextField1.getText();
                    String query="update user_details set password=? where user_name=?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, password);
                    pst.setString(2, username);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Password Updated");
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            validate.setText("* Password size between 8 to 12");
            jTextField2.setText("");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void recivedOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recivedOrdersActionPerformed
        // TODO add your handling code here:.
        jTabbedPane1.setSelectedIndex(4);
        String username= jLabel2.getText();
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/supply_chain_management","root","");
            if(con!=null)
            {
                String query="select order_id,manufacturer,product_name,product_category,Quantity,Delivery_address,Expected_delivery_date from orderToSupplier where Supplier_name=?";
                pst=con.prepareStatement(query);
                pst.setString(1, username);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    DefaultTableModel tb =(DefaultTableModel)jTable3.getModel();
                    tb.setRowCount(0);
                    tb.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_recivedOrdersActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               SupplierDash sup= new SupplierDash();
              sup.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addLot;
    private javax.swing.JTextField category;
    private javax.swing.JButton change_pass;
    private javax.swing.JTextField comName;
    private javax.swing.JTextField company_name;
    private javax.swing.JPanel destination;
    private javax.swing.JTextField destiny;
    private javax.swing.JTextField exp;
    private javax.swing.JButton inventory;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField name;
    private javax.swing.JButton orderDetails;
    private javax.swing.JTextField partner;
    private javax.swing.JButton place;
    private javax.swing.JButton placeOrder;
    private javax.swing.JTextField prod_category;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField quant;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField rate;
    private javax.swing.JButton recivedOrders;
    private javax.swing.JTextField t_mode;
    private javax.swing.JLabel validate;
    // End of variables declaration//GEN-END:variables
}
